import { Translation, Product } from './types';

export const CONTENT: Record<'en' | 'ar', Translation> = {
  en: {
    nav: {
      home: 'Home',
      catalog: 'Bouquets',
      about: 'Our Story',
      contact: 'Order Now',
      language: 'العربية',
    },
    hero: {
      title: 'Layalina Flowers',
      subtitle: 'Exquisite bouquets for all your special occasions. Weddings, Engagements, and Custom Gifts.',
      cta: 'View Collection',
      location: 'Based in Quesna, Menoufia - Delivering Everywhere',
    },
    features: {
      step1Title: 'Choose Your Design',
      step1Desc: 'Select from our catalog of natural or satin ribbon bouquets, or request a custom design.',
      step2Title: 'Handcrafted with Love',
      step2Desc: 'Expertly arranged in Quesna with attention to every detail.',
      step3Title: 'Delivery Anywhere',
      step3Desc: 'We deliver to any area. Your bouquet arrives fresh and beautiful.',
    },
    catalog: {
      title: 'Our Collection',
      wedding: 'Wedding',
      engagement: 'Engagement',
      gifts: 'Gifts',
      custom: 'Request Custom Design',
      orderBtn: 'Order on WhatsApp',
    },
    about: {
      title: 'About Us',
      desc: 'Welcome to Layalina Flowers in Quesna, Menoufia. We specialize in creating unforgettable moments with our flowers. Whether you need natural blooms for a wedding or our special handmade satin ribbon bouquets that last forever, we are here to serve you. We deliver to all areas.',
      quote: 'Flowers are the music of the ground. From earth\'s lips spoken without sound.',
    },
    contact: {
      title: 'Order Your Bouquet',
      subtitle: 'Fill out the details below to order via WhatsApp',
      name: 'Your Name',
      address: 'Address (City/Area)',
      phone: 'Phone Number',
      date: 'Date of Occasion',
      occasion: 'Occasion Type',
      notes: 'Notes (Colors, Special requests)',
      imageNote: 'Note: You can send a reference photo directly in the WhatsApp chat after clicking "Send Order".',
      submit: 'Send Order to WhatsApp',
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      catalog: 'الكتالوج',
      about: 'من نحن',
      contact: 'اطلب الآن',
      language: 'English',
    },
    hero: {
      title: 'زهور ليالينا',
      subtitle: 'أجمل بوكيهات الورد لكل مناسباتكم السعيدة. خطوبة، أفراح، وهدايا مميزة.',
      cta: 'تصفح المجموعة',
      location: 'مقرنا قويسنا، المنوفية - وبنوصل لأي مكان',
    },
    features: {
      step1Title: 'اختر التصميم',
      step1Desc: 'اختر من كتالوج الورد الطبيعي أو بوكيهات الستان الهاند ميد المميزة.',
      step2Title: 'تجهيز بكل حب',
      step2Desc: 'بنجهز طلبك بأعلى جودة واهتمام بأدق التفاصيل.',
      step3Title: 'توصيل لأي منطقة',
      step3Desc: 'بنوصل طلبك لأي مكان انت عايزه، يوصلك في ميعاده وبالشكل اللي تحبه.',
    },
    catalog: {
      title: 'تشكيلتنا المميزة',
      wedding: 'زفاف',
      engagement: 'خطوبة وشبكة',
      gifts: 'هدايا',
      custom: 'طلب تصميم خاص',
      orderBtn: 'اطلب عبر الواتساب',
    },
    about: {
      title: 'من نحن',
      desc: 'أهلاً بكم في زهور ليالينا من قلب قويسنا، المنوفية. إحنا هنا عشان نشارككم فرحتكم بأجمل بوكيهات الورد. سواء كنت بتدور على ورد طبيعي فريش أو بوكيهات الستان الهاند ميد اللي بتعيش طول العمر، إحنا بنعملك اللي انت عايزه وبنوصل لأي منطقة.',
      quote: 'الزهور هي لغة المحبة التي يفهمها الجميع دون كلمات.',
    },
    contact: {
      title: 'سجل طلبك',
      subtitle: 'املأ البيانات وسيتم تحويلك للواتساب لإتمام الحجز',
      name: 'الاسم',
      address: 'العنوان (المدينة/المنطقة)',
      phone: 'رقم التليفون',
      date: 'معاد المناسبة',
      occasion: 'نوع المناسبة',
      notes: 'ملاحظات (الألوان، شكل البوكيه، إلخ)',
      imageNote: 'ملحوظة: تقدر تبعت صورة البوكيه اللي عاجبك في شات الواتساب بعد الضغط على إرسال.',
      submit: 'إرسال الطلب للواتساب',
    },
  },
};

// Updated products to match the visual style of the user's local images
export const PRODUCTS: Product[] = [
  {
    id: '1',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.02 PM.jpeg',
    category: 'gift',
    titleEn: 'Elegant Bouquet Collection',
    titleAr: 'بوكيه أنيق مميز',
  },
  {
    id: '2',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.02 PM (1).jpeg',
    category: 'gift',
    titleEn: 'Beautiful Flower Arrangement',
    titleAr: 'ترتيب زهور جميل',
  },
  {
    id: '3',
    image: '/images/bridal bouquet بوكيه عروسة.jfif',
    category: 'wedding',
    titleEn: 'Royal Bridal Bouquet',
    titleAr: 'بوكيه زفاف ملكي',
  },
  {
    id: '4',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.02 PM (2).jpeg',
    category: 'gift',
    titleEn: 'Romantic Pink Bouquet',
    titleAr: 'بوكيه رومانسي وردي',
  },
  {
    id: '5',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.02 PM (3).jpeg',
    category: 'engagement',
    titleEn: 'Engagement Special',
    titleAr: 'بوكيه خطوبة مميز',
  },
  {
    id: '6',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.02 PM (4).jpeg',
    category: 'gift',
    titleEn: 'Luxury Flower Bouquet',
    titleAr: 'بوكيه فاخر',
  },
  {
    id: '7',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.02 PM (5).jpeg',
    category: 'gift',
    titleEn: 'Elegant White & Pink',
    titleAr: 'بوكيه أبيض ووردي أنيق',
  },
  {
    id: '8',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.02 PM (6).jpeg',
    category: 'gift',
    titleEn: 'Classic Red Roses',
    titleAr: 'بوكيه ورد أحمر كلاسيكي',
  },
  {
    id: '9',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.02 PM (7).jpeg',
    category: 'engagement',
    titleEn: 'Special Occasion Bouquet',
    titleAr: 'بوكيه مناسبة خاصة',
  },
  {
    id: '10',
    image: '/images/WhatsApp Image 2025-11-18 at 10.36.03 PM.jpeg',
    category: 'gift',
    titleEn: 'Mixed Flower Arrangement',
    titleAr: 'ترتيب زهور متنوع',
  },
  {
    id: '11',
    image: '/images/download.jfif',
    category: 'gift',
    titleEn: 'Handmade Bouquet',
    titleAr: 'بوكيه هاند ميد',
  },
  {
    id: '12',
    image: '/images/download (1).jfif',
    category: 'gift',
    titleEn: 'Beautiful Arrangement',
    titleAr: 'ترتيب جميل',
  },
  {
    id: '13',
    image: '/images/download (2).jfif',
    category: 'gift',
    titleEn: 'Elegant Flower Design',
    titleAr: 'تصميم زهور أنيق',
  },
  {
    id: '14',
    image: '/images/download (3).jfif',
    category: 'gift',
    titleEn: 'Special Bouquet',
    titleAr: 'بوكيه مميز',
  },
];